# --- --- --- ---
# .bashrc local settig for XXXXX
# --- --- --- ---

# --- base file load ---
if [ -f ~/dotfiles/bash/.bashrc ]; then
	. ~/dotfiles/bash/.bashrc
fi

# prompt
#PS1="[\! \u@\h:\w]$ "
#PS1="{\[\033[32m\]\!\[\033[0m\] \u@\h\[\033[34m\]:\[\033[0m\]\[\033[36m\]\w\[\033[0m\]}$ "

# --- alias ---
# alias ls='ls -F -G'

